package com.csst.hotelCrawler.entity;

import java.util.Date;

public class CommentStatistic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentStatistic.id
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentStatistic.count
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentStatistic.hotelId
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    private Integer hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentStatistic.commentMonth
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    private Date commentmonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentStatistic.hotelName
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    private String hotelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentStatistic.neu
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    private String neu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentStatistic.pos
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    private String pos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentStatistic.neg
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    private String neg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentStatistic.id
     *
     * @return the value of commentStatistic.id
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentStatistic.id
     *
     * @param id the value for commentStatistic.id
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentStatistic.count
     *
     * @return the value of commentStatistic.count
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentStatistic.count
     *
     * @param count the value for commentStatistic.count
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentStatistic.hotelId
     *
     * @return the value of commentStatistic.hotelId
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentStatistic.hotelId
     *
     * @param hotelid the value for commentStatistic.hotelId
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentStatistic.commentMonth
     *
     * @return the value of commentStatistic.commentMonth
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    public Date getCommentmonth() {
        return commentmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentStatistic.commentMonth
     *
     * @param commentmonth the value for commentStatistic.commentMonth
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    public void setCommentmonth(Date commentmonth) {
        this.commentmonth = commentmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentStatistic.hotelName
     *
     * @return the value of commentStatistic.hotelName
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    public String getHotelname() {
        return hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentStatistic.hotelName
     *
     * @param hotelname the value for commentStatistic.hotelName
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    public void setHotelname(String hotelname) {
        this.hotelname = hotelname == null ? null : hotelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentStatistic.neu
     *
     * @return the value of commentStatistic.neu
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    public String getNeu() {
        return neu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentStatistic.neu
     *
     * @param neu the value for commentStatistic.neu
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    public void setNeu(String neu) {
        this.neu = neu == null ? null : neu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentStatistic.pos
     *
     * @return the value of commentStatistic.pos
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    public String getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentStatistic.pos
     *
     * @param pos the value for commentStatistic.pos
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    public void setPos(String pos) {
        this.pos = pos == null ? null : pos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentStatistic.neg
     *
     * @return the value of commentStatistic.neg
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    public String getNeg() {
        return neg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentStatistic.neg
     *
     * @param neg the value for commentStatistic.neg
     *
     * @mbggenerated Thu Apr 16 14:34:24 CST 2015
     */
    public void setNeg(String neg) {
        this.neg = neg == null ? null : neg.trim();
    }
}