package com.csst.hotelCrawler.entity;

import java.util.Date;

public class HotelComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelComment.id
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelComment.hotelId
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private Integer hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelComment.name
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelComment.trip
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private String trip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelComment.checkInDate
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private Date checkindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelComment.roomtype
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private String roomtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelComment.score
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private Float score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelComment.scoreAll
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private String scoreall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelComment.commentDate
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private Date commentdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelComment.comment
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private String comment;
    
    private String feel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelComment.id
     *
     * @return the value of hotelComment.id
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelComment.id
     *
     * @param id the value for hotelComment.id
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelComment.hotelId
     *
     * @return the value of hotelComment.hotelId
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelComment.hotelId
     *
     * @param hotelid the value for hotelComment.hotelId
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelComment.name
     *
     * @return the value of hotelComment.name
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelComment.name
     *
     * @param name the value for hotelComment.name
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelComment.trip
     *
     * @return the value of hotelComment.trip
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public String getTrip() {
        return trip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelComment.trip
     *
     * @param trip the value for hotelComment.trip
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setTrip(String trip) {
        this.trip = trip == null ? null : trip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelComment.checkInDate
     *
     * @return the value of hotelComment.checkInDate
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public Date getCheckindate() {
        return checkindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelComment.checkInDate
     *
     * @param checkindate the value for hotelComment.checkInDate
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setCheckindate(Date checkindate) {
        this.checkindate = checkindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelComment.roomtype
     *
     * @return the value of hotelComment.roomtype
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public String getRoomtype() {
        return roomtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelComment.roomtype
     *
     * @param roomtype the value for hotelComment.roomtype
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setRoomtype(String roomtype) {
        this.roomtype = roomtype == null ? null : roomtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelComment.score
     *
     * @return the value of hotelComment.score
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelComment.score
     *
     * @param score the value for hotelComment.score
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelComment.scoreAll
     *
     * @return the value of hotelComment.scoreAll
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public String getScoreall() {
        return scoreall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelComment.scoreAll
     *
     * @param scoreall the value for hotelComment.scoreAll
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setScoreall(String scoreall) {
        this.scoreall = scoreall == null ? null : scoreall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelComment.commentDate
     *
     * @return the value of hotelComment.commentDate
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public Date getCommentdate() {
        return commentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelComment.commentDate
     *
     * @param commentdate the value for hotelComment.commentDate
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setCommentdate(Date commentdate) {
        this.commentdate = commentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelComment.comment
     *
     * @return the value of hotelComment.comment
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelComment.comment
     *
     * @param comment the value for hotelComment.comment
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

	public String getFeel() {
		return feel;
	}

	public void setFeel(String feel) {
		this.feel = feel;
	}
    
    
}