package com.csst.hotelCrawler.entity;

public class CommentStatisticBreakfast {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentStatistic_breakfast.id
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentStatistic_breakfast.count
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentStatistic_breakfast.hotelId
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    private Integer hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentStatistic_breakfast.hotelName
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    private String hotelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentStatistic_breakfast.neu
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    private String neu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentStatistic_breakfast.pos
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    private String pos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentStatistic_breakfast.neg
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    private String neg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentStatistic_breakfast.id
     *
     * @return the value of commentStatistic_breakfast.id
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentStatistic_breakfast.id
     *
     * @param id the value for commentStatistic_breakfast.id
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentStatistic_breakfast.count
     *
     * @return the value of commentStatistic_breakfast.count
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentStatistic_breakfast.count
     *
     * @param count the value for commentStatistic_breakfast.count
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentStatistic_breakfast.hotelId
     *
     * @return the value of commentStatistic_breakfast.hotelId
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentStatistic_breakfast.hotelId
     *
     * @param hotelid the value for commentStatistic_breakfast.hotelId
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentStatistic_breakfast.hotelName
     *
     * @return the value of commentStatistic_breakfast.hotelName
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    public String getHotelname() {
        return hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentStatistic_breakfast.hotelName
     *
     * @param hotelname the value for commentStatistic_breakfast.hotelName
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    public void setHotelname(String hotelname) {
        this.hotelname = hotelname == null ? null : hotelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentStatistic_breakfast.neu
     *
     * @return the value of commentStatistic_breakfast.neu
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    public String getNeu() {
        return neu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentStatistic_breakfast.neu
     *
     * @param neu the value for commentStatistic_breakfast.neu
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    public void setNeu(String neu) {
        this.neu = neu == null ? null : neu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentStatistic_breakfast.pos
     *
     * @return the value of commentStatistic_breakfast.pos
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    public String getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentStatistic_breakfast.pos
     *
     * @param pos the value for commentStatistic_breakfast.pos
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    public void setPos(String pos) {
        this.pos = pos == null ? null : pos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentStatistic_breakfast.neg
     *
     * @return the value of commentStatistic_breakfast.neg
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    public String getNeg() {
        return neg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentStatistic_breakfast.neg
     *
     * @param neg the value for commentStatistic_breakfast.neg
     *
     * @mbggenerated Wed Apr 29 14:38:50 CST 2015
     */
    public void setNeg(String neg) {
        this.neg = neg == null ? null : neg.trim();
    }
}