package com.csst.hotelCrawler.entity;

import com.ccst.bigdata.entity.Pojo;

public class HotelRoomInfo extends Pojo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelRoomInfo.id
     *
     * @mbggenerated Thu Apr 09 17:20:49 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelRoomInfo.roomType
     *
     * @mbggenerated Thu Apr 09 17:20:49 CST 2015
     */
    private String roomtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelRoomInfo.hotelId
     *
     * @mbggenerated Thu Apr 09 17:20:49 CST 2015
     */
    private Integer hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelRoomInfo.hoteName
     *
     * @mbggenerated Thu Apr 09 17:20:49 CST 2015
     */
    private String hotename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelRoomInfo.description
     *
     * @mbggenerated Thu Apr 09 17:20:49 CST 2015
     */
    private String description;
    
    
    private String webroomid;

    /**
	 * @return the webroomid
	 */
	public String getWebroomid() {
		return webroomid;
	}

	/**
	 * @param webroomid the webroomid to set
	 */
	public void setWebroomid(String webroomid) {
		this.webroomid = webroomid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelRoomInfo.id
     *
     * @return the value of hotelRoomInfo.id
     *
     * @mbggenerated Thu Apr 09 17:20:49 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelRoomInfo.id
     *
     * @param id the value for hotelRoomInfo.id
     *
     * @mbggenerated Thu Apr 09 17:20:49 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelRoomInfo.roomType
     *
     * @return the value of hotelRoomInfo.roomType
     *
     * @mbggenerated Thu Apr 09 17:20:49 CST 2015
     */
    public String getRoomtype() {
        return roomtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelRoomInfo.roomType
     *
     * @param roomtype the value for hotelRoomInfo.roomType
     *
     * @mbggenerated Thu Apr 09 17:20:49 CST 2015
     */
    public void setRoomtype(String roomtype) {
        this.roomtype = roomtype == null ? null : roomtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelRoomInfo.hotelId
     *
     * @return the value of hotelRoomInfo.hotelId
     *
     * @mbggenerated Thu Apr 09 17:20:49 CST 2015
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelRoomInfo.hotelId
     *
     * @param hotelid the value for hotelRoomInfo.hotelId
     *
     * @mbggenerated Thu Apr 09 17:20:49 CST 2015
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelRoomInfo.hoteName
     *
     * @return the value of hotelRoomInfo.hoteName
     *
     * @mbggenerated Thu Apr 09 17:20:49 CST 2015
     */
    public String getHotename() {
        return hotename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelRoomInfo.hoteName
     *
     * @param hotename the value for hotelRoomInfo.hoteName
     *
     * @mbggenerated Thu Apr 09 17:20:49 CST 2015
     */
    public void setHotename(String hotename) {
        this.hotename = hotename == null ? null : hotename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelRoomInfo.description
     *
     * @return the value of hotelRoomInfo.description
     *
     * @mbggenerated Thu Apr 09 17:20:49 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelRoomInfo.description
     *
     * @param description the value for hotelRoomInfo.description
     *
     * @mbggenerated Thu Apr 09 17:20:49 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}