package com.csst.hotelCrawler.entity;

import java.util.Date;

import com.ccst.bigdata.entity.Pojo;

public class HotelPrice extends Pojo{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelPrice.id
     *
     * @mbggenerated Fri Apr 10 11:16:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelPrice.price
     *
     * @mbggenerated Fri Apr 10 11:16:19 CST 2015
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelPrice.priceDate
     *
     * @mbggenerated Fri Apr 10 11:16:19 CST 2015
     */
    private Date pricedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelPrice.crawlerDate
     *
     * @mbggenerated Fri Apr 10 11:16:19 CST 2015
     */
    private Date crawlerdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelPrice.roomId
     *
     * @mbggenerated Fri Apr 10 11:16:19 CST 2015
     */
    private Integer roomid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelPrice.id
     *
     * @return the value of hotelPrice.id
     *
     * @mbggenerated Fri Apr 10 11:16:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelPrice.id
     *
     * @param id the value for hotelPrice.id
     *
     * @mbggenerated Fri Apr 10 11:16:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelPrice.price
     *
     * @return the value of hotelPrice.price
     *
     * @mbggenerated Fri Apr 10 11:16:19 CST 2015
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelPrice.price
     *
     * @param price the value for hotelPrice.price
     *
     * @mbggenerated Fri Apr 10 11:16:19 CST 2015
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelPrice.priceDate
     *
     * @return the value of hotelPrice.priceDate
     *
     * @mbggenerated Fri Apr 10 11:16:19 CST 2015
     */
    public Date getPricedate() {
        return pricedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelPrice.priceDate
     *
     * @param pricedate the value for hotelPrice.priceDate
     *
     * @mbggenerated Fri Apr 10 11:16:19 CST 2015
     */
    public void setPricedate(Date pricedate) {
        this.pricedate = pricedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelPrice.crawlerDate
     *
     * @return the value of hotelPrice.crawlerDate
     *
     * @mbggenerated Fri Apr 10 11:16:19 CST 2015
     */
    public Date getCrawlerdate() {
        return crawlerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelPrice.crawlerDate
     *
     * @param crawlerdate the value for hotelPrice.crawlerDate
     *
     * @mbggenerated Fri Apr 10 11:16:19 CST 2015
     */
    public void setCrawlerdate(Date crawlerdate) {
        this.crawlerdate = crawlerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelPrice.roomId
     *
     * @return the value of hotelPrice.roomId
     *
     * @mbggenerated Fri Apr 10 11:16:19 CST 2015
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelPrice.roomId
     *
     * @param roomid the value for hotelPrice.roomId
     *
     * @mbggenerated Fri Apr 10 11:16:19 CST 2015
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }
}