package com.csst.hotelCrawler.entity;

import java.util.Date;

public class HotelScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelScore.id
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelScore.datasource
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private String datasource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelScore.hotelId
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private Integer hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelScore.position
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private Double position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelScore.facility
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private Double facility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelScore.service
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private Double service;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelScore.health
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private Double health;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelScore.score
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    private Double score;
    
   
    private Date crawlerdate;
    

    /**
	 * @return the crawlerdate
	 */
	public Date getCrawlerdate() {
		return crawlerdate;
	}

	/**
	 * @param crawlerdate the crawlerdate to set
	 */
	public void setCrawlerdate(Date crawlerdate) {
		this.crawlerdate = crawlerdate;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelScore.id
     *
     * @return the value of hotelScore.id
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelScore.id
     *
     * @param id the value for hotelScore.id
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelScore.datasource
     *
     * @return the value of hotelScore.datasource
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public String getDatasource() {
        return datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelScore.datasource
     *
     * @param datasource the value for hotelScore.datasource
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setDatasource(String datasource) {
        this.datasource = datasource == null ? null : datasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelScore.hotelId
     *
     * @return the value of hotelScore.hotelId
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelScore.hotelId
     *
     * @param hotelid the value for hotelScore.hotelId
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelScore.position
     *
     * @return the value of hotelScore.position
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public Double getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelScore.position
     *
     * @param position the value for hotelScore.position
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setPosition(Double position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelScore.facility
     *
     * @return the value of hotelScore.facility
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public Double getFacility() {
        return facility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelScore.facility
     *
     * @param facility the value for hotelScore.facility
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setFacility(Double facility) {
        this.facility = facility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelScore.service
     *
     * @return the value of hotelScore.service
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public Double getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelScore.service
     *
     * @param service the value for hotelScore.service
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setService(Double service) {
        this.service = service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelScore.health
     *
     * @return the value of hotelScore.health
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public Double getHealth() {
        return health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelScore.health
     *
     * @param health the value for hotelScore.health
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setHealth(Double health) {
        this.health = health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelScore.score
     *
     * @return the value of hotelScore.score
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelScore.score
     *
     * @param score the value for hotelScore.score
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    public void setScore(Double score) {
        this.score = score;
    }
}