package com.csst.hotelCrawler.dao;

import com.ccst.bigdata.dao.DAO;
import com.csst.hotelCrawler.entity.HotelRoomInfo;

public interface HotelRoomInfoDao extends DAO<HotelRoomInfo> {
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelRoomInfo
     *
     * @mbggenerated Thu Apr 09 17:20:49 CST 2015
     */
    void insert(HotelRoomInfo record);

    
}