package com.csst.hotelCrawler.dao;

import java.util.List;

import com.csst.hotelCrawler.entity.HotelComment;

public interface HotelCommentDao {
   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelComment
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    int insert(HotelComment record);
    
    List<String> queryExistHotelId();   
    
    List<HotelComment> queryAll();
    
    void update(HotelComment hc);

}