package com.csst.hotelCrawler.dao;

import java.util.List;

import com.csst.hotelCrawler.entity.HotelScore;
import com.csst.hotelCrawler.entity.vo.HotelScoreVo;

public interface HotelScoreDao {
   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelScore
     *
     * @mbggenerated Mon Apr 13 09:10:00 CST 2015
     */
    int insert(HotelScore record);
    
    int insertTmp(HotelScore record);
    
    int countTmp();
    
    /**
     * 整体备份历史数据
     */
    void copyToHotelScore();
    
    void copyToHistory();
    
    
    void deleteHotelScore();
    
    void deleteHotelScoreTmp(); 
    

    List<HotelScoreVo> queryByHotelId(int[] ids);
    
    List<HotelScore> queryScoreHistroy(int[] ids);
  
}