package com.csst.hotelCrawler.dao;

import com.ccst.bigdata.dao.DAO;
import com.csst.hotelCrawler.entity.HotelPrice;

public interface HotelPriceDao extends DAO<HotelPrice>{
   
    void insert(HotelPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelPrice
     *
     * @mbggenerated Fri Apr 10 11:16:19 CST 2015
     */
    
}